name: Errata
description: Submit an issue with the book
title: "[Errata]: "
labels: ["errata", "triage"]
projects: ["raspberrypipress/official-raspberry-pi-beginners-guide-5e"]
assignees:
  - bjepson
  - ghalfacree
body:
  - type: markdown
    attributes:
      value: |
        Have you found an error in the book or something that is unclear? Please let us know so we can update it in a future printing.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: If you share your email address with us, we may contact you for more information.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: format
    attributes:
      label: What format of the book has this error?
      multiple: true
      options:
        - Print
        - PDF
        - ePub
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: What language of the book has this error?
      multiple: true
      options:
        - Danish (DK)
        - English (EN)
        - French (FR)
        - German (DE)
        - Greek (GR)
        - Italian (IT)
        - Japanese (JP)
        - Norwegian (NO)
        - Portuguese (PT)
        - Spanish (ES)
        - Swedish (SE)
    validations:
      required: true
  - type: input
    id: pageno
    attributes:
      label: Page Number or Section
      description: Where was the error located?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Detailed description
      description: Please let us know in detail about this error.
    validations:
      required: true
